/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JuegoApp;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;


/*
    Juego: Piedra papel o tijera
        
        
 */
public class PanelPrincipal extends javax.swing.JFrame {

    private static final boolean QUE_NO_SE_VEA = false;
    private static final boolean QUIERO_QUE_SE_VEA = true;

    private static final int DETECTO_JUGADA_PIEDRA = 1;
    private static final int DETECTO_JUGADA_PAPEL = 2;
    private static final int DETECTO_JUGADA_TIJERA = 3;

    private static final int EMPATE = 0;
    private static final int GANO_JUGADOR_UNO = 1;
    private static final int GANO_JUGADOR_DOS = 2;

    private static final Component DEF_POSICION_FRAME = null;
    
    private static final boolean NO_CAMBIAR_TAMANIO = false;
    
    private static final String NOMBRE_VENTANA_JUEGO = "ventana juego";
    private static final String NOMBRE_VENTANA_MENU = "ventana menu";

    private CardLayout cl;

    private Usuario jugador;
    private Bot bob;
    private Juego piedraPapelTijera;

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();

        ocultarJugadasBot();
        jugador = new Usuario();
        bob = new Bot();
        piedraPapelTijera = new Juego();

        cl = new CardLayout();//creamos el componente que nos permite organizarnos con los paneles en la app

        jPanelBase.setLayout(cl);

        jPanelBase.add(jPanelMenu, NOMBRE_VENTANA_MENU);
        jPanelBase.add(jPanelJuego, NOMBRE_VENTANA_JUEGO);

        cl.show(jPanelBase, NOMBRE_VENTANA_MENU);

        configuracionFrame(jPanelMenu.getPreferredSize());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelJuego = new javax.swing.JPanel();
        BotonPiedra = new javax.swing.JButton();
        BotonPapel = new javax.swing.JButton();
        BotonTijera = new javax.swing.JButton();
        jLabelImagenPiedraBot = new javax.swing.JLabel();
        jLabelImagenPapelBot = new javax.swing.JLabel();
        jLabelImagenTijeraBot = new javax.swing.JLabel();
        jLabelTextoGanador = new javax.swing.JLabel();
        jButtonRegresarMenu = new javax.swing.JButton();
        jPanelMenu = new javax.swing.JPanel();
        jLabelTituloJuego = new javax.swing.JLabel();
        jLabelTituloNombreJugador = new javax.swing.JLabel();
        jTextFieldNombreJugador = new javax.swing.JTextField();
        jTextFieldNombreBot = new javax.swing.JTextField();
        jLabelTituloNombreBot = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        jPanelBase = new javax.swing.JPanel();

        BotonPiedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JuegoApp/piedra.png"))); // NOI18N
        BotonPiedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPiedraMouseClicked(evt);
            }
        });

        BotonPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JuegoApp/papel.png"))); // NOI18N
        BotonPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPapelMouseClicked(evt);
            }
        });

        BotonTijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JuegoApp/tijera.png"))); // NOI18N
        BotonTijera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonTijeraMouseClicked(evt);
            }
        });

        jLabelImagenPiedraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JuegoApp/piedraBot.png"))); // NOI18N

        jLabelImagenPapelBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JuegoApp/papelBot.png"))); // NOI18N

        jLabelImagenTijeraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JuegoApp/tijeraBot.png"))); // NOI18N

        jLabelTextoGanador.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabelTextoGanador.setText("Gano tal jugador!");

        jButtonRegresarMenu.setBackground(new java.awt.Color(0, 102, 0));
        jButtonRegresarMenu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonRegresarMenu.setText("Regresar");
        jButtonRegresarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegresarMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelJuegoLayout = new javax.swing.GroupLayout(jPanelJuego);
        jPanelJuego.setLayout(jPanelJuegoLayout);
        jPanelJuegoLayout.setHorizontalGroup(
            jPanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJuegoLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabelImagenPiedraBot, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(jLabelImagenPapelBot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImagenTijeraBot)
                .addGap(229, 229, 229))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJuegoLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jPanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJuegoLayout.createSequentialGroup()
                        .addComponent(BotonPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(jPanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJuegoLayout.createSequentialGroup()
                                .addComponent(BotonPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(BotonTijera, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTextoGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJuegoLayout.createSequentialGroup()
                        .addComponent(jButtonRegresarMenu)
                        .addGap(22, 22, 22))))
        );
        jPanelJuegoLayout.setVerticalGroup(
            jPanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRegresarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonTijera, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BotonPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BotonPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJuegoLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImagenPiedraBot, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelImagenPapelBot)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJuegoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabelImagenTijeraBot, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabelTextoGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jLabelTituloJuego.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabelTituloJuego.setText("Piedra, papel o tijera!");

        jLabelTituloNombreJugador.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabelTituloNombreJugador.setText("Jugador:");

        jTextFieldNombreJugador.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldNombreJugador.setText("nombre jugador");

        jTextFieldNombreBot.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldNombreBot.setText("nombre de bot");

        jLabelTituloNombreBot.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabelTituloNombreBot.setText("Bot:");

        jButtonJugar.setBackground(new java.awt.Color(0, 102, 51));
        jButtonJugar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonJugar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJugar.setText("Jugar!");
        jButtonJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJugarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloJuego)
                    .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelMenuLayout.createSequentialGroup()
                            .addComponent(jLabelTituloNombreJugador)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelMenuLayout.createSequentialGroup()
                            .addComponent(jLabelTituloNombreBot)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonJugar)
                                .addComponent(jTextFieldNombreBot, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelTituloJuego)
                .addGap(81, 81, 81)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloNombreJugador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloNombreBot))
                .addGap(49, 49, 49)
                .addComponent(jButtonJugar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Detectar que el boton de piedra fue clickeado
     *
     * @param evt
     */
    private void BotonPiedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPiedraMouseClicked
        jugador.eligioPiedra();

        ocultarJugadasBot();

        mostrarJugadaAleatoria();
        mostrarGanador();
    }//GEN-LAST:event_BotonPiedraMouseClicked

    /**
     * Detectar que el boton papel fue clickeado
     *
     * @param evt
     */
    private void BotonPapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPapelMouseClicked
        jugador.eligioPapel();

        ocultarJugadasBot();

        mostrarJugadaAleatoria();
        mostrarGanador();
    }//GEN-LAST:event_BotonPapelMouseClicked

    /**
     * Detectar que el boton tijero fue clickeado
     *
     * @param evt
     */
    private void BotonTijeraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTijeraMouseClicked
        jugador.eligioTijera();

        ocultarJugadasBot();

        mostrarJugadaAleatoria();
        mostrarGanador();
    }//GEN-LAST:event_BotonTijeraMouseClicked

    private void jButtonJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJugarMouseClicked
        System.out.println("Cambiar de ventana a ventana de juego");
        jugador.ahoraTeLlamas(jTextFieldNombreJugador.getText());
        bob.ahoraTeLlamas(jTextFieldNombreBot.getText());
        cl.show(jPanelBase, NOMBRE_VENTANA_JUEGO);
        jPanelJuego.setPreferredSize(new Dimension(1280,720));
        configuracionFrame(jPanelJuego.getPreferredSize());
    }//GEN-LAST:event_jButtonJugarMouseClicked

    private void jButtonRegresarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresarMenuMouseClicked
        System.out.println("Regresar al menu del juego");
        cl.show(jPanelBase, NOMBRE_VENTANA_MENU);
        configuracionFrame(jPanelMenu.getPreferredSize());
    }//GEN-LAST:event_jButtonRegresarMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPapel;
    private javax.swing.JButton BotonPiedra;
    private javax.swing.JButton BotonTijera;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonRegresarMenu;
    private javax.swing.JLabel jLabelImagenPapelBot;
    private javax.swing.JLabel jLabelImagenPiedraBot;
    private javax.swing.JLabel jLabelImagenTijeraBot;
    private javax.swing.JLabel jLabelTextoGanador;
    private javax.swing.JLabel jLabelTituloJuego;
    private javax.swing.JLabel jLabelTituloNombreBot;
    private javax.swing.JLabel jLabelTituloNombreJugador;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelJuego;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JTextField jTextFieldNombreBot;
    private javax.swing.JTextField jTextFieldNombreJugador;
    // End of variables declaration//GEN-END:variables

    /**
     * Muestra la jugada aleatoria del bot
     */
    private void mostrarJugadaAleatoria() {
        switch (bob.generaJugadaAleatoria()) {
            case DETECTO_JUGADA_PIEDRA:
                //mostrar jugada piedra
                jLabelImagenPiedraBot.setVisible(QUIERO_QUE_SE_VEA);
                break;
            case DETECTO_JUGADA_PAPEL:
                //mostrar jugada papel
                jLabelImagenPapelBot.setVisible(QUIERO_QUE_SE_VEA);
                break;
            case DETECTO_JUGADA_TIJERA:
                //mostrar jugada tijera
                jLabelImagenTijeraBot.setVisible(QUIERO_QUE_SE_VEA);
        }
    }

    /**
     * Oculte los iconos de las jugadas del bot
     */
    private void ocultarJugadasBot() {
        jLabelImagenPapelBot.setVisible(QUE_NO_SE_VEA);
        jLabelImagenPiedraBot.setVisible(QUE_NO_SE_VEA);
        jLabelImagenTijeraBot.setVisible(QUE_NO_SE_VEA);
    }

    /**
     * Muestra la informacion en la app de quien gano
     */
    private void mostrarGanador() {
        switch (piedraPapelTijera.decimeQuienGano(jugador, bob)) {
            case EMPATE:
                jLabelTextoGanador.setText("EMPATE");
                break;
            case GANO_JUGADOR_UNO:
                jLabelTextoGanador.setText("GANO " + jugador.decimeTuNombre());
                break;
            case GANO_JUGADOR_DOS:
                jLabelTextoGanador.setText("GANO " + bob.decimeTuNombre());

        }
    }

    /**
     * Ajustar el tamaño del frame al del panel requerido
     *
     * @param tamVentanaPreferido es el tamaño de la ventana requerida
     */
    private void configuracionFrame(Dimension tamVentanaPreferido) {
        jPanelBase.setPreferredSize(tamVentanaPreferido);//cambio el taman preferido al panel base
        this.pack();//ajusta el tamaño del frame al de la ventana requerida
        this.setResizable(NO_CAMBIAR_TAMANIO);// no quiero que se pueda modificar el tamaño de la ventana
        this.setLocationRelativeTo(DEF_POSICION_FRAME);//asigno la posicion relativa a un componente nulo para que quede en el centro la ventana
    }

}
